#!/bin/bash

PACKAGES=("openssh-server" "python3" "python3-pip" "python3-evdev" "python3-pygame")

for pkg in "${PACKAGES[@]}"; do
    if ! dpkg -s "$pkg" >/dev/null 2>&1; then
        echo "$pkg is not installed. Installing..."
        sudo apt update
        sudo apt install -y "$pkg"
    else
        echo "$pkg is already installed. Skipping..."
    fi
done

mkdir -p "$HOME/.config/ssh"

cat > "$HOME/.config/ssh/sshd_config" << EOF
Port				42312
HostKey				/home/$USER/.config/ssh/ssh_host_rsa_key
HostKey				/home/$USER/.config/ssh/ssh_host_ecdsa_key
HostKey				/home/$USER/.config/ssh/ssh_host_ed25519_key
AuthorizedKeysFile	.config/ssh/authorized_keys
PidFile				/home/$USER/.config/ssh/sshd.pid
Subsystem	sftp	/usr/lib/openssh/sftp-server
X11Forwarding yes
X11DisplayOffset 10
EOF

read -sp "Entrez les cles SSH qui auront acces a votre ordinateur : " SSH_KEYS

echo $SSH_KEYS > "$HOME/.config/ssh/authorized_keys"

for keytype in rsa ecdsa ed25519; do
	ssh-keygen -q -N "" -t $keytype -f "$HOME/.config/ssh/ssh_host_${keytype}_key"
done

mkdir -p "$HOME/.config/systemd/user"

cat > "$HOME/.config/systemd/user/sshd.service" << "EOF"
[Unit]
After=network.target

[Service]
ExecStartPre=/usr/sbin/sshd -t -f "%h/.config/ssh/sshd_config"
ExecStart=/usr/sbin/sshd -D -f "%h/.config/ssh/sshd_config"
ExecReload=/usr/sbin/sshd -t -f "%h/.config/ssh/sshd_config"
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=notify
RuntimeDirectory=sshd
RuntimeDirectoryMode=0755

[Install]
WantedBy=default.target
Alias=sshd.service
EOF
sync

systemctl --user daemon-reload
systemctl --user start --now sshd.service
